services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_GATEWAY_URL: http://10.42.0.19:5000
    ports:
      - "5173:80"
    depends_on:
      - backend
